#!/bin/bash

case $BLOCK_BUTTON in
    1) exec ~/.config/i3/sp play ;; # left click
    4) exec ~/.config/i3/sp next ;; # scroll up
    5) exec ~/.config/i3/sp prev ;; # scroll down
esac

if exec ~/.config/i3/sp status | grep 'Paused' > /dev/null; then
    printf '\xef\x81\x8b ' # fa-pause
else
    printf '\xef\x81\x8c ' # fa-play
fi
exec ~/.config/i3/sp current-oneline
